local project = require("fpga_sv.project")
local util = require("fpga_sv.util")
local M = {}

local owner = "nvim_fpga_sv"
local marker = "// generated by nvim_fpga_sv; DO NOT EDIT\n"

local function quote(value)
  value = value:gsub("\\", "/")
  if value:find("[%s\"]") then
    return '"' .. value:gsub('"', '\\"') .. '"'
  end
  return value
end

local function define_lines(defines)
  local names, lines = {}, {}
  for name in pairs(defines or {}) do
    names[#names + 1] = name
  end
  table.sort(names)
  for _, name in ipairs(names) do
    local value = defines[name]
    lines[#lines + 1] = "-D" .. name .. (value == true and "" or "=" .. tostring(value))
  end
  return lines
end

local function model_lines(model, relative_base, portable)
  local lines = {}
  local function display(path)
    return quote(portable and util.relative(path, relative_base) or path)
  end
  for _, dir in ipairs(model.include_dirs or {}) do
    lines[#lines + 1] = "-I" .. display(dir)
  end
  vim.list_extend(lines, define_lines(model.defines))
  for _, dir in ipairs(model.library_dirs or {}) do
    lines[#lines + 1] = "-y " .. display(dir)
  end
  if #(model.library_extensions or {}) > 0 then
    lines[#lines + 1] = "+libext+" .. table.concat(model.library_extensions, "+")
  end
  vim.list_extend(lines, model.flags or {})
  for _, file in ipairs(model.files or {}) do
    lines[#lines + 1] = display(file)
  end
  return lines
end

local function set_difference(full, portable)
  local result = project.empty(full.root, full.profile)
  result.top = full.top
  result.lint = vim.deepcopy(full.lint)

  local function path_diff(field)
    local existing = {}
    for _, value in ipairs(portable[field] or {}) do
      existing[util.path_key(value)] = true
    end
    for _, value in ipairs(full[field] or {}) do
      if not existing[util.path_key(value)] then
        result[field][#result[field] + 1] = value
      end
    end
  end
  path_diff("files")
  path_diff("include_dirs")
  path_diff("library_dirs")

  for name, value in pairs(full.defines or {}) do
    if portable.defines[name] ~= value then
      result.defines[name] = value
    end
  end
  local function scalar_diff(field)
    local existing = {}
    for _, value in ipairs(portable[field] or {}) do
      existing[tostring(value)] = true
    end
    for _, value in ipairs(full[field] or {}) do
      if not existing[tostring(value)] then
        result[field][#result[field] + 1] = value
      end
    end
  end
  scalar_diff("library_extensions")
  scalar_diff("flags")
  return result
end

local function owned_content(path)
  local content = util.read_file(path)
  if not content then
    return true
  end
  if path:sub(-5) == ".json" then
    local ok, decoded = pcall(vim.json.decode, content)
    return ok and decoded and decoded._owner == owner
  end
  return content:sub(1, #marker) == marker
end

local function write_owned(path, content)
  if util.exists(path) and not owned_content(path) then
    return nil, "拒绝覆盖非插件管理的文件: " .. path
  end
  local old = util.read_file(path)
  if old == content then
    return false
  end
  local ok, err = util.atomic_write(path, content)
  if not ok then
    return nil, err
  end
  return true
end

local function portable_config(layer, profile_name)
  local profile = layer.profiles and layer.profiles[profile_name]
  if not profile then
    return nil
  end
  return {
    source_sets = layer.source_sets or {},
    profiles = { [profile_name] = profile },
    default_profile = profile_name,
  }
end

local function build_all(workspace)
  local effective = workspace.config.effective
  local built = {}
  local names = vim.tbl_keys(effective.profiles)
  table.sort(names)
  for _, name in ipairs(names) do
    local full, errors = project.build(workspace.root, effective, name)
    if not full then
      return nil, errors
    end
    local portable_layer = portable_config(workspace.config.portable, name)
    local portable = project.empty(workspace.root, name)
    if portable_layer then
      portable, errors = project.build(workspace.root, portable_layer, name)
      if not portable then
        return nil, errors
      end
    end
    built[name] = {
      full = full,
      portable = portable,
      local_only = set_difference(full, portable),
    }
  end
  return built
end

local function json_content(data)
  data._owner = owner
  return vim.json.encode(data) .. "\n"
end

function M.run(workspace)
  local built, errors = build_all(workspace)
  if not built then
    workspace.errors = errors
    return nil, errors
  end

  local options = workspace.config.effective
  local project_dir = util.path(options.project_output_dir, workspace.root)
  local local_dir = vim.fs.joinpath(
    options.state_dir,
    "projects",
    util.root_hash(workspace.root),
    "generated"
  )
  local pending = {}

  for name, models in pairs(built) do
    local project_f = vim.fs.joinpath(project_dir, name .. ".f")
    local local_f = vim.fs.joinpath(local_dir, name .. ".f")
    local project_lines = model_lines(models.portable, project_dir, true)
    local local_lines = {
      "-F " .. quote(project_f),
    }
    vim.list_extend(local_lines, model_lines(models.local_only, workspace.root, false))

    local project_json = vim.fs.joinpath(project_dir, name .. ".slang.json")
    local local_json = vim.fs.joinpath(local_dir, name .. ".slang.json")
    pending[#pending + 1] = { project_f, marker .. table.concat(project_lines, "\n") .. "\n" }
    pending[#pending + 1] = { local_f, marker .. table.concat(local_lines, "\n") .. "\n" }
    pending[#pending + 1] = {
      project_json,
      json_content({
        profile = name,
        buildFile = project_f,
        top = models.portable.top,
        hash = util.hash(project_lines),
      }),
    }
    pending[#pending + 1] = {
      local_json,
      json_content({
        profile = name,
        buildFile = local_f,
        top = models.full.top,
        hash = util.hash(local_lines),
      }),
    }
    built[name].artifacts = {
      project_filelist = project_f,
      local_filelist = local_f,
      project_slang = project_json,
      local_slang = local_json,
    }
  end

  local default_name = options.default_profile
  local default_entry = built[default_name]
  if default_entry then
    pending[#pending + 1] = {
      vim.fs.joinpath(project_dir, "slang.json"),
      json_content({
        profile = default_name,
        buildFile = default_entry.artifacts.project_filelist,
        top = default_entry.portable.top,
      }),
    }
  end
  local active_entry = built[workspace.active_profile]
  if active_entry then
    pending[#pending + 1] = {
      vim.fs.joinpath(local_dir, "slang.json"),
      json_content({
        profile = workspace.active_profile,
        buildFile = active_entry.artifacts.local_filelist,
        top = active_entry.full.top,
      }),
    }
  end

  -- 先检查所有目标的所有权，冲突时不写入任何新产物。
  for _, item in ipairs(pending) do
    if util.exists(item[1]) and not owned_content(item[1]) then
      local conflict = "生成冲突: " .. item[1]
      workspace.errors = { conflict }
      return nil, { conflict }
    end
  end

  for _, item in ipairs(pending) do
    local _, err = write_owned(item[1], item[2])
    if err then
      workspace.errors = { err }
      return nil, { err }
    end
  end

  workspace.generation = workspace.generation + 1
  workspace.errors = {}
  workspace.models = built
  workspace.artifacts = built[workspace.active_profile].artifacts
  util.emit("FpgaSvProjectGenerated", {
    root = workspace.root,
    profile = workspace.active_profile,
    generation = workspace.generation,
  })
  return built
end

function M.activate(workspace)
  local entry = workspace.models and workspace.models[workspace.active_profile]
  if not entry then
    return nil, "活动 Profile 尚未生成"
  end
  local path = vim.fs.joinpath(
    workspace.config.effective.state_dir,
    "projects",
    util.root_hash(workspace.root),
    "generated",
    "slang.json"
  )
  local content = json_content({
    profile = workspace.active_profile,
    buildFile = entry.artifacts.local_filelist,
    top = entry.full.top,
  })
  local _, err = write_owned(path, content)
  if err then
    return nil, err
  end
  return path
end

return M
